version: "3"
services:

  mongo:
    image: mongo:4.0
    volumes:
      - mongo_data:/data/db
    # ports:
    #   - 27017:27017

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 4567:4567
    depends_on:
      - mongo
    environment:
      - BIND_ADDRESS=0.0.0.0
      - APP_ENV=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

volumes:
  mongo_data:
